version: "3.7"

services:
  prestashop:
    image: prestashop/prestashop:1.7-7.1-apache
    env_file:
      - .env.local
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    env_file:
      - .env.local

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - .env.local